[package]
name = "ship-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
description = "Local server library for Ship"

[dependencies]
ship-core = { workspace = true, features = ["axum", "kameo"] }
ship-macros.workspace = true

axum.workspace = true
futures-util.workspace = true
indexmap.workspace = true
kameo.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
utoipa.workspace = true
utoipa-axum.workspace = true
uuid.workspace = true

[lints]
workspace = true
