[package]
name = "ship-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
description = "Shared data and contextual errors for Ship"

[features]
axum = ["dep:axum"]
kameo = ["dep:kameo"]

[dependencies]
axum = { workspace = true, optional = true }
indexmap.workspace = true
kameo = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
tracing.workspace = true
utoipa.workspace = true
uuid.workspace = true

[lints]
workspace = true
