[package]
name = "ship-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
description = "HTTP client library for Ship"

[dependencies]
ship-core.workspace = true

reqwest.workspace = true
serde.workspace = true
url.workspace = true
tokio.workspace = true

[lints]
workspace = true
