[package]
name = "ship-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
description = "HTTP client library and full-screen client for Ship"

[dependencies]
ship-core.workspace = true

crokey.workspace = true
crossterm = { workspace = true, features = ["bracketed-paste", "event-stream"] }
futures-util.workspace = true
indexmap.workspace = true
notify-debouncer-mini.workspace = true
ratatui.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sse-stream.workspace = true
url.workspace = true
tokio.workspace = true
toml.workspace = true
tokio-stream.workspace = true

[lints]
workspace = true
